name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false # Wait finishing other parallel jobs
      matrix:
        targets:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            filename: git-branch-delete-merged-linux-x86_64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            filename: git-branch-delete-merged-linux-arm64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            filename: git-branch-delete-merged-win-x86_64.exe
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            filename: git-branch-delete-merged-win-arm64.exe
          - target: x86_64-apple-darwin
            os: macos-latest
            filename: git-branch-delete-merged-mac-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            filename: git-branch-delete-merged-mac-arm64
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            target: ${{ matrix.targets.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --locked --target=${{ matrix.targets.target }}
      - name: Rename result
        run: |
          rm target/${{ matrix.targets.target }}/release/git-branch-delete-merged.d
          cp target/${{ matrix.targets.target }}/release/git-branch-delete-merged* ${{ matrix.targets.filename }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: git-branch-delete-merged-artifacts
          path: ${{ matrix.targets.filename }}
