name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false # Wait finishing other parallel jobs
      matrix:
        targets:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            filename: git-branch-delete-merged-Linux-x86_64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            filename: git-branch-delete-merged-Linux-arm64
          - target: x86_64-apple-darwin
            os: macos-latest
            filename: git-branch-delete-merged-Darwin-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            filename: git-branch-delete-merged-Darwin-arm64
          # - target: i686-pc-windows-msvc
          #   os: windows-latest
          #   filename: git-branch-delete-merged-Windows-32bit.exe
          # - target: x86_64-pc-windows-msvc
          #   os: windows-latest
          #   filename: git-branch-delete-merged-Windows-x86_64.exe
          # - target: aarch64-pc-windows-msvc
          #   os: windows-latest
          #   filename: git-branch-delete-merged-Windows-arm64.exe
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            target: ${{ matrix.targets.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --locked --target=${{ matrix.targets.target }}
      - name: Rename result
        run: |
          rm target/${{ matrix.targets.target }}/release/git-branch-delete-merged.d
          cp target/${{ matrix.targets.target }}/release/git-branch-delete-merged* ${{ matrix.targets.filename }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ matrix.targets.filename }}

  release:
    name: Create release page
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            git-branch-delete-merged-Linux-x86_64
            git-branch-delete-merged-Linux-arm64
            git-branch-delete-merged-Darwin-x86_64
            git-branch-delete-merged-Darwin-arm64
          # git-branch-delete-merged-Windows-32bit.exe
          # git-branch-delete-merged-Windows-x86_64.exe
          # git-branch-delete-merged-Windows-arm64.exe
